# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test-Psi4

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          auto-activate-base: false
          python-version: '3.10' 
          
      - name: Initialize Conda for the shell
        run: |
          which conda
          # Initialize Conda
          conda init bash
          # Restart the shell to apply changes
          bash 
          
      - name: Create Conda environment and install Psi4
        run: |
          # Create Conda environment with Python 3.10
          conda create --name psi4_env python=3.10 -y
          # Install Psi4 via Conda
          # some issue with qcelemental where imports fail for pydantic>2
          conda uninstall -n psi4_env pydantic
          conda install -n psi4_env -c conda-forge pydantic=1.*
          conda install -n psi4_env -c psi4 psi4 -y

      - name: Verify Python version with conda run
        run: |
          # Verify Python version inside the environment
          conda run -n psi4_env python --version
          echo "import psi4" > asd.py
          echo "print(psi4.__version__)" >> asd.py
          conda run -n psi4_env python asd.py

      - name: Set up virtual environment and run tests
        run: |

          conda run -n psi4_env pip install -e .
          conda run -n psi4_env pip install pyscf pytest
          cp -r tests/data data
          conda run -n psi4_env pytest tests/test_chemistry.py
          conda run -n psi4_env pytest tests/test_adapt.py
